### ISSUE TITLE
fix restart script button - clear related tasks

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#14]
1. ran through a follow-up script (police), finished with two relevant tasks. 
2. I clicked on 'אתחל שיחה' and ran through the script, this time with no tasks.

at the end of this 2nd round, I got to the tasks from the 1st round :

![image](https://user-images.githubusercontent.com/3581741/60178120-5773e080-9823-11e9-9f13-d9dc98ea4f80.png)

expected behavior: clicking the 'אתחול שיחה' will delete the records of the old task on DB.

**Comment by akariv** [comment]
This was done on purpose - I wouldn't want a single click to delete all progress and updates on the report.
I think that a better ux would be to keep them open and open new tasks in case they don't already exist.
wdyt?

**Comment by noamoss** [comment]
@akariv I see your point, but it is risky because sometimes tasks will stop being relevant, following the new answers the user will type in. 

I assume that most of the times a user will 'restart' when a new detail or a condition appears, or after discovering a mistake entered before. We can not assume the user (i.e. the Mokdan) really knows which tasks are still relevant or not. 

Therefore, I believe a better way to handle it would be adding a mid-step, asking the user "האם תרצו למחוק או לשמור את המשימות הקיימות למקרה?" [option A: "למחוק", option B:"לשמור"].

How does it sound?

**Comment by akariv** [comment]
I think that the agent that worked on these tasks would know what is still relevant and what is not, and if they want they can just close all the old ones - there's not going to be that many tasks anyway, so checking 5 items in a list is not a big deal IMO.

**Comment by noamoss** [comment]
>I think that the agent that worked on these tasks would know what is still relevant and what is not

nope, we can not assume our users knows anything about relevant procedres per case.

>..if they want they can just close all the old ones - there's not going to be that many tasks anyway, so checking 5 items in a list is not a big deal IMO.

now I see where we are not speaking in same terms: when I asked to delete tasks, I meant erasing them from the DB. When you are speaking of 'closing' them you mean to mark them as completed. There is a difference between these two actions: deleting a task (when restarting a script) means it will not be saved or displayed later, while "closing" it (i.e. marking it as complete) means the worker/boss/judge will see the task as a step that was taken and compelted. It will remain on record, and that's a problem when we are talking about restarting our script, to figure our what are the right tasks to take.

makes sense?

**Comment by noamoss** [comment]
(for now, moved out of the urgent task column, for  discussion)

**Comment by noamoss** [comment]
@akariv 

ok, here is my idea - which also covers another (separate) problem: usually an agent would like to restart the guidance during the talk (in case of taking the wrong path).

Let's make the 'restart' button visible only during the first follow-up conversation, and disappears once the guidance is completed. Doing so, while deleting the currently open tasks, is basically what we need.

**Comment by noamoss** [comment]
@akariv now, when we are done implementing all scripts, and about to start the pilot, let's implement my recent idea ^^^.

Leaving the situation as is will make a mess in the pilot.

**Comment by noamoss** [comment]
checked on live and approved.
