### ISSUE TITLE
add a manual task

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#15]
this feature should be visible and available only for records/reports that ran through the follow-up script (in other words, when the agent sees the case for the first time, or after clicking 'אתחול שיחה', this button should be availble.

button location:
![image](https://user-images.githubusercontent.com/3581741/60178292-d10bce80-9823-11e9-892b-421ec668454c.png)

button label: "הוספת משימה"

when I click the button, a new task wiill be added at the end of the shown list:

![image](https://user-images.githubusercontent.com/3581741/60178480-51caca80-9824-11e9-9733-c8b820441a13.png)

1. a default task title text holder: "משימה חדשה לביצוע - לחצו כאן כדי לערוך".
2. an edit icon, to enable user to update the task title.
(the rest of the fields/values should be populated similar to the previous tasks)

notice it should be integrated and taken into account on #26 #35

**Comment by noamoss** [comment]
@akariv could you estimate how long would it take to add this feature and reassign to me?

**Comment by akariv** [comment]
@noamoss 

Did you mean:

> in other words, when the agent sees the case for the first time, or after clicking 'אתחול שיחה', this button should **not** be availble

?

**Comment by noamoss** [comment]
....yes.

**Comment by akariv** [comment]
@noamoss 

Did you mean:

> in other words, when the agent sees the case for the first time, or after clicking 'אתחול שיחה', this button should **not** be availble

?

**Comment by noamoss** [comment]
checked on live and approved. @akariv great work.

**Comment by noamoss** [comment]
@akariv 

hopla  - found a small issue: the standard place holder says "click here to edit" which is great, but might be confusing when looking on the same task card on the left column:

![image](https://user-images.githubusercontent.com/3581741/64476558-95cd3a80-d198-11e9-92e8-581a978167c9.png)

Two possible solutions:
1. Just change the task title to:

"משימה חדשה לעריכה"

2. or, even better, add the "לחצו כאן לעריכה" to appear next to (and as part of) the edit (pencil) icon, instad of being part of the task title.

**Comment by akariv** [comment]
Selected (1) as  (2) would be too cumbersome to repeat for all tasks.
