### ISSUE TITLE
can't upload files on agent side

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#17]
same happened 3 times (sentry popped up, I sent one report)

![image](https://user-images.githubusercontent.com/3581741/60351476-867a8580-99ce-11e9-9e3a-a4e0b043e655.png)

**Comment by noamoss** [comment]
compared quickly with the user-side script, could not notice a difference.

**Comment by akariv** [comment]
instead of `cmd.uploader(key,uploader)` should use `cmd.uploader(record,key,uploader)`
changed in `script.json`

**Comment by noamoss** [comment]
@akariv sorry, got me to the following error/crash (sent sentry report as well

![image](https://user-images.githubusercontent.com/3581741/60542257-26604800-9d1c-11e9-99d6-b78ede628288.png)

**Comment by akariv** [comment]
Seems that there's a missing field on the backend side or some incompatibility there - added better console logs to help debug these scenarios.

**Comment by akariv** [comment]
In this case it's `file1`...
(generally these should be removed from the script as we don't need to collect `fileX` any more)

**Comment by noamoss** [comment]
@akariv 

>In this case it's file1...

'weird as we have `file1` being used (and working) on the user side as well (otherwise, I could not upload the first two files for the case I am testing):

![image](https://user-images.githubusercontent.com/3581741/60746256-9a9e2400-9f86-11e9-8e1f-62e15e33e6b9.png)


> (generally these should be removed from the script as we don't need to collect fileX any more)

when I tried to do what your wrote (moving all the fileX from the agent script, leaving the cmd.fileuploader() function without returning value, the site stopped crashing, but I still got a "תקלה בהעלאת הקובץ" in the UI:

![image](https://user-images.githubusercontent.com/3581741/60746208-5579f200-9f86-11e9-835d-9acff29021b9.png)


![image](https://user-images.githubusercontent.com/3581741/60746137-0cc23900-9f86-11e9-8d2c-9fb088c9baaa.png)

**Comment by noamoss** [comment]
sorry, I missed the previous comment (with the new cmd.uploader structure). It works fine. Closing issue.
