### ISSUE TITLE
cmd.selectGovOrgs(record) retrurns irrelevant organizations (not following scenarios)

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#18]
For example, [this org](https://reportit-cms.obudget.org/admin/plugins/content-manager/organization/4?redirectUrl=/plugins/content-manager/organization?_limit=10&_page=1&_sort=id&source=content-manager) includes the following:

```{
  "scenarios": [
    {
      "offender": "מאבטח/ת"
    }
  ]
}
```

but the yes/no question jumps when offender is 'משטרה'

**Comment by akariv** [comment]
Couldn't reproduce. 
Does this happen on the deployed site too?

**Comment by akariv** [comment]
Ah, found the source - 

you deleted this code two days ago:
https://github.com/hasadna/reportit-agent/commit/a20e11e30503ceaa175066201c40291c125c732b#diff-bfac120f645f556f13e7e7d4016fbb45L36

I'm leaving it assigned to you.

**Comment by noamoss** [comment]
@akariv crashed when got to the relevant step (gvorgso selector):

![image](https://user-images.githubusercontent.com/3581741/60541918-45120f00-9d1b-11e9-94d9-e89a6067531f.png)

**Comment by akariv** [comment]
Did you check this time that your local code is in sync with the remote one
(that was the problem last time)

**Comment by akariv** [comment]
Okay, problem here was that the attached infocard slug was not recognized - fixed now.

**Comment by noamoss** [comment]
@akariv 

not sure I understood the problem - was it something I did wrong? (if so, please explain what), or you had to fix it in the code?

**Comment by noamoss** [comment]
checked and approved.
