### ISSUE TITLE
can't create tasks through code fucntions (can't add Justice Ministry anti racism tasks)

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#21]
might be a follow-up of #19 (which I did not fully understand the cause of the problem)

- in the script.json we are asking the agent whether the user is interested in sharing the info with the justice ministry (yes/anonymously/no):

![image](https://user-images.githubusercontent.com/3581741/60754627-6e1cf300-9fec-11e9-8b8a-2cd6cad8b6b3.png)

but when clicking "yes" (1) or "anonymously" (2), the relevant functions do not run (no task is being added + the relevant console.log messages do not appear)

![image](https://user-images.githubusercontent.com/3581741/60754589-e7681600-9feb-11e9-91b0-f79c19ecbafa.png)

![image](https://user-images.githubusercontent.com/3581741/60754689-7fb2ca80-9fed-11e9-9a35-e7766bfd3709.png)

**Comment by akariv** [comment]
the "on:event -> card_name" metadata shortcut does not work with functions. It simply adds a single task based on its name which and the response value.
For more complex logic, you should revert to the regular flow - collect into a variable and use `cmd.func(record)` to use the logic.

If it's important, I can add the cmd.func logic to the on:event handling as well.

**Comment by akariv** [comment]
(Although, in this case using 'collect' would reduce the number of needed functions to 1 instead of 2)

**Comment by noamoss** [comment]
got you, let me try your offer first, and if needed I will bring it up again. Thanks.

**Comment by noamoss** [comment]
works  fine, closing the issue.
