### ISSUE TITLE
organization info card: omit null (empty) fields and label + add missing details

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#22]
* add missing values, split emails and make them clickable. For example [on this info card](https://reportit-cms.obudget.org/admin/plugins/content-manager/organization/7?redirectUrl=/plugins/content-manager/organization?_limit=10&_page=1&_sort=id&source=content-manager):
![image](https://user-images.githubusercontent.com/3581741/61567260-97775d80-aa87-11e9-8fd4-6562b95c0aea.png)

* [ ]  the phone nubmer and fax are not displayed
* [ ]   the two emails should be separated by a commma
* [ ] emails should be clickable (open a "mailto:" window)

* [ ] on `justice_ministry_legal_assistance` infocard, the `Phone response details` is not displayed

* [ ]  If there is no value (i.e. null) - no need to show the field nor the label:

![image](https://user-images.githubusercontent.com/3581741/60757044-fb247400-a00d-11e9-8c15-1c136b0aa733.png)

-----

more examples, following QA report:

> 
> 
> + בעמודה השמאלית בחלק של ״היחידה הממשלתית לתיאום המאבק בגזענות״
> כתובת המייל של גליה בונה- כתובת מייל: antiracismunit@justice.gov.il null
> 
> + המרכז לנפגעי גזענות (התנועה הרפורמית): מוקד מידע, סיוע וליווי משפטי
> כתובת מייל: stop.racism@ircc.org.il null

**Comment by noamoss** [comment]
reopening:

1. https://reportit-cms.obudget.org/admin/plugins/content-manager/infocard?_limit=10&_page=1&_sort=id&source=content-manager:
(website does not appear on the card)


![image](https://user-images.githubusercontent.com/3581741/61596904-f5d04780-ac11-11e9-9c50-c708e40cec29.png)

2. https://reportit-cms.obudget.org/admin/plugins/content-manager/infocard?_limit=10&_page=1&_sort=id&source=content-manager

(description field shows null)

![image](https://user-images.githubusercontent.com/3581741/61596916-1b5d5100-ac12-11e9-826e-8e4bb4fc79c7.png)

**Comment by akariv** [comment]
<img width="595" alt="Screen Shot 2019-07-22 at 9 17 19" src="https://user-images.githubusercontent.com/265333/61610342-8da95200-ac61-11e9-9645-8df9ba4d7a61.png">

Do you see the problem?

**Comment by akariv** [comment]
Anyway, I fixed the field name and corrected the DB structure.
