### ISSUE TITLE
enable to add Task with slug (variable) to script

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#23]
i.e. task "shareWithOrg:mahash"

**Comment by akariv** [comment]
I added an `addTask` function, expecting these parameters:
- record
- task name slug
- optional organization slug e.g. mahash
- optional extra slugs of infocards

**Comment by noamoss** [comment]
@akariv please share/show a usage example. 

I am thinking about opening a wiki functions page for future documentation. What do you think?

**Comment by akariv** [comment]
Usage examples:

https://github.com/hasadna/reportit-scripts/search?l=YAML&q=addTask
