### ISSUE TITLE
how to handle reports with email as only communication method

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#25]
QA feedback:

> במקרה שאמצע התקשורת שמתלונן נתן הוא מייל- איך המוקדן מנהל שיחה איתו ושואל שאלות? נעם הציע שלמוקדן יהיה פורמט של תשובה שעיקרה הוא לקבל מספר טלפון.

**Comment by noamoss** [comment]
@akariv what do you think about solving this via script? (i.e. if there is only email details to a report, the 'agent' user will have a single Task - to send the reportit-user (הפונה) a ready email, explaining we need an alternative online communication method, and what is about to happen.

Sounds good? 
Any other idea?

**Comment by noamoss** [comment]
Another option is working on a solution for #30, which will also enable an asynouchrnic agent-user communication.

**Comment by akariv** [comment]
@noamoss can you detail here the solution we agreed on?

**Comment by noamoss** [comment]
@akariv 

if the 'email' was chosen as **a single** communication method, the agent side will get the following follow-up items:

1. message:
שלחו את המייל הבא לכתובת המייל שהעביר/ה הפונה, מלאו את הפרטים החסרים:

> שמי ______, מהמוקד למאבק בגזענות ממסדית.
> קיבלתי את הפרטים ששלחת אלינו ב-______. יש לי כמה שאלות שחשוב לי לשאול ולברר איתך לגבי המקרה, כדי שאוכל להציע לך דרכי פעולה אפשריות. זה קצת קשה לברר את כל הפרטים הללו במייל. האם ישנה דרך אחרת בה נוכל ליצור קשר? איך אפשר יהיה לשוחח איתך או להתכתב איתך? 
> 
> את/ה מוזמנ/ת גם ליצור איתי קשר ב:_______ בימים __________ בשעות _________.
> 
> תודה,
> 

2. task:
task_title: "משלוח בקשה לאמצעי קשר נוספים לפונה"
task_description: שלחו את הנוסח הבא, עם התיקונים וההשלמות הנדרשות.

> 
> שלום __________,
> שמי ______, מהמוקד למאבק בגזענות ממסדית.
> קיבלתי את הפרטים ששלחת אלינו ב-______. יש לי כמה שאלות שחשוב לי לשאול ולברר איתך לגבי המקרה, כדי שאוכל להציע לך דרכי פעולה אפשריות. זה קצת קשה לברר את כל הפרטים הללו במייל. האם ישנה דרך אחרת בה נוכל ליצור קשר? איך אפשר יהיה לשוחח איתך או להתכתב איתך? 
> 
> את/ה מוזמנ/ת גם ליצור איתי קשר ב:_______ בימים __________ בשעות _________.
> 
> תודה,


ניתן לסמן את המשימה כהושלמה לאחר שהתקבל מענה עם פרטים נוספים, או אם לא התקבלה התייחסות לאחר שני נסיונות נוספים ליצור קשר עם הפונה. לאחר הזנת פרטי התקשרות חדשים והשלמת המשימה יש ללחוץ על "אתחול שיחה" לצורך קבלת הנחיה מפורטת.

**Comment by akariv** [comment]
Implemented as specified, just fyi that this contradicts with https://github.com/hasadna/reportit-agent/issues/14 as there is not 'restart script' button when tasks are showing.

**Comment by noamoss** [comment]
@akariv you are right. can we add a link to restart the script into this task description (i.e. לחצו כאן לאחר הזנת פרטי ההתקשרות, לקבלת הנחיות לשיחה)?

**Comment by noamoss** [comment]
@akariv checked on live and approved the implementation, please see my question above ^^^^ to tackle the problem you raised.

**Comment by akariv** [comment]
Adding a custom button to a task is not possible atm.

**Comment by noamoss** [comment]
@akariv I did not mean a custom button - just a link in the message, which will trigger the thread restart. Not possible? Any other idea to handle this?

**Comment by akariv** [comment]
Reassigning to @noamoss as this needs some definition work.

**Comment by akariv** [comment]
We could add a new button to the tasks view (as it was before).
Perhaps once #30 is implemented it will make things easier (i.e no need to
restart the thread, just pick it up where it was 'paused')

**Comment by noamoss** [comment]
@akariv : 

*    task:

>     task_title: "משלוח בקשה לאמצעי קשר נוספים לפונה"
>     task_description: שלחו את הנוסח הבא, עם התיקונים וההשלמות הנדרשות.
> 
>     שלום __________,
>     שמי , מהמוקד למאבק בגזענות ממסדית.
>     קיבלתי את הפרטים ששלחת אלינו ב-. יש לי כמה שאלות שחשוב לי לשאול ולברר איתך לגבי המקרה, כדי שאוכל להציע לך דרכי פעולה אפשריות. זה קצת קשה לברר את כל הפרטים הללו במייל. האם ישנה דרך אחרת בה נוכל ליצור קשר? איך אפשר יהיה לשוחח איתך או להתכתב איתך?
> 
>     את/ה מוזמנ/ת גם ליצור איתי קשר ב:_______ בימים __________ בשעות _________.
> 
>     תודה,

> ניתן לסמן את המשימה כהושלמה לאחר שהתקבל מענה עם פרטים נוספים, או אם לא התקבלה התייחסות לאחר שני נסיונות נוספים ליצור קשר עם הפונה. לאחר הזנת פרטי התקשרות חדשים והשלמת המשימה יש [ללחוץ כאן](#) לצורך קבלת הנחיה מפורטת.


![image](https://user-images.githubusercontent.com/3581741/64493778-1cfbda80-d28d-11e9-92c6-29ccf9c0dcd9.png)


* The link in the task description above should trigger one of the two:
A. restart the thread, this time with the new details (preferred options)
B. duplicate the current record --> delete the current record --> switch display towards the cloned record to start the automated thread.

**Comment by noamoss** [comment]
@akariv 

>Perhaps once #30 is implemented it will make things easier (i.e no need to
restart the thread, just pick it up where it was 'paused')

makes sense. Let's wait and see, if not we can go the other direction (adding the button we had before).

**Comment by noamoss** [comment]
checked on live and approved.
