### ISSUE TITLE
handle no follow-up tasks scenario

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#31]
QA/User feedback:

>  אם סיימנו את התסריט והפונה לא רצה להגיש תלונה לאף גוף, אין לי כמוקדן משימות- האם להציע למתלונן שוב פעם את האפשרויות (ולהתחיל את התסריט מחדש)- אלה האפשרויות שלנו.

this sounds like a good idea - let's write a standard method that will:

1. check the number of open tasks connected with the current report
2. if the totalTaks == 0 show the following question:
"סיימנו את השיחה, מבלי שקיבלת את הסכמת הפונה לנקוט פעולה כלשהי. 
הסבר/י לו שזה המצב וברר/י אם ירצו לחזור על הנקודות שהועלו, כדי לחשוב שוב על הדברים

האם הפונה מבקש לשנות חלק מהתשובות?
כן
לא"

3. if the agent clicks on 'כן' we will restart the thread, without cleaning the the 2nd column (so they can scroll up and remind the user their previous answers, and maybe even copy/paste some parts".

**Comment by noamoss** [comment]
@akariv feel free to come up with other/simpler soultions

**Comment by noamoss** [comment]
notice this issue is related to #13

**Comment by noamoss** [comment]
reopening as this task was not implemented:

![image](https://user-images.githubusercontent.com/3581741/64476450-59e5a580-d197-11e9-848d-5ac3dd1cdfb3.png)

**Comment by akariv** [comment]
How's that an indication it wasn't implemented? That's what happens when the agent clicks on 'no' in the last question:
<img width="1421" alt="Screen Shot 2019-09-08 at 22 49 16" src="https://user-images.githubusercontent.com/265333/64493618-fdfc4900-d28a-11e9-8219-96dad44466bd.png">

**Comment by noamoss** [comment]
@akariv sorry, my bad.
