### ISSUE TITLE
auto update/refresh agent main display

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#36]
QA / User feedback:

> המוקדן חייב לעשות refresh כדי לראות שינויים. שמתי לב שאם הדף של המוקדן פתוח, ובאותו זמן הגשתי תלונה, היא לא הופיעה, החדשה, בדף של המוקדן.  לדוגמא כשסימנתי משהו כ״ טיפול הושלם״, הוא לא הופיע בספירה שמימין. אחרי רפרוש זה הופיע.

I find this feedback relevant because I assume real-world agent to open the window at the beginning of the shift, taking care of the open tasks or the new report, and then leaving it open for the rest of the day. 

Without updating (or refreshing) the page once in a while, they might miss new reports - and who knows, it can take a week or two until they close the tab and browse again to the agent main page.

**Comment by akariv** [comment]
List will now auto-update whenever window is refocused (e.g. was in another tab and user switched to it) or we go back from editing a single report.

**Comment by noamoss** [comment]
@akariv  **This is what I planned to write as a comment**:


> I am reopening this issue, to consider an extra modification assuming a very common usage scenario: an agent opens their day surveying the open calls. Then they leave the tab open check it again every 2-3 hours. The current solution won't show them any indication for a new report. I assume fetching automatically new records is a (too) big deal here.  What about using the Ynet method (i.e. auto-refresh the page every 20 minutes or so)?

But then I checked on the live site and my new report just showed up while I was logged into the agent view... what's the trick?


![image](https://user-images.githubusercontent.com/3581741/62426458-dcd59500-b6ed-11e9-8653-7e8dffbbf0b5.png)

**Comment by akariv** [comment]
**List will now auto-update whenever window is refocused (e.g. was in another tab and user switched to it)** :)

**Comment by noamoss** [comment]
oh... sorry, misunderstood. 

so my question is still valid (and therefore I will reopen this issue):

The current solution won't show them any indication for a new report. I assume fetching automatically new records is a (too) big deal here. What about using the Ynet method (i.e. auto-refresh the page every 20 minutes or so)?

**Comment by akariv** [comment]
Please describe the scenario you're thinking about that is not covered by window being refocused.

**Comment by akariv** [comment]
@noamoss ^^

**Comment by noamoss** [comment]
:+1:

**Comment by noamoss** [comment]
:star: :star: :star: :star: :star:
