### ISSUE TITLE
script (guard): add task to look for the relevant company if it is unkown by the user

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#41]

**Comment by noamoss** [comment]
@akariv It is harder now for me to implement this issue, because the local version of report-it agent is connected to the common script, and because I am depending on you to approve my PR before being able to check the result.

Please take over (you can use https://github.com/hasadna/reportit-scripts/commit/73e9c10348c98ea03128dd4667335bcead88e02a, on  https://github.com/hasadna/reportit-scripts/pull/2 as a base)

**Comment by akariv** [comment]
you can change the url in the runner.run() call to point to a local
location (e.g. 'assets/script.json')

Then just copy the script.json you're generating to src/assets/ and you can
test locally

**Comment by akariv** [comment]
@noamoss

**Comment by noamoss** [comment]
thanx. 
done and deployed.
