### ISSUE TITLE
Create new script format

### ISSUE THREAD

**Issue by akariv** [hasadna/reportit-agent#45]
We want to have a simpler format for defining scripts, so that it's:
- more readable and editable
- in-line with how hatool works
- fits our use case better
- less hacks and boilerplate

**Comment by akariv** [comment]
@noamoss @oferb 

I've created a proposal for this new format, it can be found here:

https://github.com/hasadna/reportit-agent/blob/master/src/assets/output.yaml

**Comment by noamoss** [comment]
@akariv I reviewed it, looks fine by me. What should happen next with this issue? How does it relate to the wider task (#25)?

**Comment by noamoss** [comment]
@akariv I am reopening this issue as there seems to be a serious bug: none of the cases works on the agent side (in other words - I can not go beynd the first 'קראתי' click). No relevant console messages:

![image](https://user-images.githubusercontent.com/3581741/64474497-5396ff80-d17e-11e9-9820-f19c1fc34113.png)

**Comment by noamoss** [comment]
works fine, thanks.
