### ISSUE TITLE
scroll arrows on report side 

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#46]
whatismybrowser.com/w/WE8CSLW

![image](https://user-images.githubusercontent.com/3581741/64700677-fd90c780-d4af-11e9-9658-086d2bede004.png)

**Comment by akariv** [comment]
Which browser / OS was that? 
The link above no longer works.

**Comment by akariv** [comment]
On my machine it does not reproduce neither on FF nor on Chrome.

**Comment by noamoss** [comment]
@akariv 
reproduced using whatismybrowser.com/w/6X8HCP5

![image](https://user-images.githubusercontent.com/3581741/70813029-76fec580-1dd1-11ea-9eb2-f0f703226abb.png)

**Comment by noamoss** [comment]
@akariv wasn't solved:

![image](https://user-images.githubusercontent.com/3581741/70833795-5189b000-1e01-11ea-9fb2-0943ce961568.png)

**Comment by akariv** [comment]
I don't have a machine in which I can reproduce this, so trying stuff blindly...

**Comment by noamoss** [comment]
@akariv cool, solved:

![image](https://user-images.githubusercontent.com/3581741/70835587-33727e80-1e06-11ea-846a-38971307be28.png)
