### ISSUE TITLE
unmarked checked option on thread replay

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#47]
whatismybrowser.com/w/WE8CSLW:

![image](https://user-images.githubusercontent.com/3581741/64701145-e0102d80-d4b0-11e9-847d-ca3e84b6646d.png)

**Comment by akariv** [comment]
As we discussed, this is caused by implementing functions that take control over the script.
All user interaction needs to be implemented in the script itself (and not in code) - also for translation reasons.

**Comment by noamoss** [comment]
@akariv  I implemented everything I could until I got stacked with https://github.com/hasadna/reportit-agent/issues/53. Please reassign to me when I can finish this part.

**Comment by akariv** [comment]
How is this related to #53? The idea was to implement this switch in the
script and not in a function, why is it related to the loop implementation?

**Comment by noamoss** [comment]
@akariv 
I hope I am not confusing things, but you wrote on your comment that...

>As we discussed, this is caused by implementing functions that take control over the script.

Since the loop/recursive implementation includes a question to the agent I can not finalize my side of removing all the functions that are taking control over the user input.

**Comment by akariv** [comment]
You can definitely remove this specific function and push it without waiting for the loop fix.

**Comment by noamoss** [comment]
@akariv are you sure?
I thought this is the problematic function you were referring to [this line](https://github.com/hasadna/reportit-scripts/blob/e9e5407e5a3de5cc9cadfa3b5be54a0e6da578a5/src/agent/script.yaml#L587) that sends the script to [this function](https://github.com/hasadna/reportit-scripts/blob/e9e5407e5a3de5cc9cadfa3b5be54a0e6da578a5/src/agent/script.yaml#L1352):

![image](https://user-images.githubusercontent.com/3581741/70812450-4cf8d380-1dd0-11ea-9f09-e95cee96272d.png)

so there are two options:
1. I did not understand which function you are talking about, please be more explicit.
2. we need to solve #53 before I can move on with this issue.

feel free to take over if you had enough of this issue, but ping me to show what did you mean.

**Comment by akariv** [comment]
I must be confused, I thought this was implemented in a function but it's not - and in fact this issue does not reproduce.
<img width="819" alt="Screen Shot 2019-12-13 at 23 28 04" src="https://user-images.githubusercontent.com/265333/70833431-61ed5b00-1e00-11ea-85e4-320ddee6e29a.png">

The loop problem happens only when calling the same function from the same location more than once in the same script, other functions are not affected by it.
Either way that bug was already resolved anyway, so the discussion is moot.
