### ISSUE TITLE
Show Mokdan readable explanation of broken script or other errors 

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#5]
The purpose is to enable the user (Mokdan) knowing that:

1. Something went wrong.
2. Understand generally what it was.

and being able to: 
3. Copy/Paste technical details/log of the error (to share with the technical team).

(this issue might somehow related to #https://github.com/hasadna/reportit-user/issues/7)

**Comment by akariv** [comment]
Added sentry support
