### ISSUE TITLE
Script uses invalid variable name 'housing_land_type'

### ISSUE THREAD

**Issue by akariv** [hasadna/reportit-agent#50]
The script uses this invalid name, which prevents continuing it once it has been set.

**Comment by noamoss** [comment]
(@akariv please notice to include issues you open on board as well, (I missed this before)

**Comment by noamoss** [comment]
this was supposed to be a local variable name (_housing_land_type). Fixed via the new script editor.

This issue was fixed but during the check I found #65.

**Comment by akariv** [comment]
Can't see it - did you deploy the new script?

**Comment by noamoss** [comment]
@akariv ...probably not - just saved the script though the editor, and rebuilt through travis. what is the missing step (and do I have the permission to perform it?)

**Comment by akariv** [comment]
I don't see any build in reporit-sctipts - maybe you built a different repo?

**Comment by noamoss** [comment]
@akariv  you are right, I assumed it should be done through the agent/user build. Just finished the reportit-scripts build, rechecked on live and approved. feel free to verify.
