### ISSUE TITLE
update translations mechanism to extract stringify function(s) textual parameters

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#52]
related to https://github.com/hasadna/reportit-agent/issues/51

include textual parameters for stringification functions in the translation process. 

a existing example would be:
```
        askShareWithOrg: async(record, question) => {
          this.infocards.appendCard('org:' + record._currentOrg.slug);
          this.content.addTo(`${question} ${record._currentOrg["Organization Name"]}?`);
        },
```

but this can be abstracted via #51

**Comment by akariv** [comment]
Done, although no script currently needs this.
