### ISSUE TITLE
update wait to consider context

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#53]
to enable recursive functions, see 
* NgoOrgsLoop
* govOrgsLoop

in the reportit-agent code

![image](https://user-images.githubusercontent.com/3581741/67722582-2f1f0d00-f9e2-11e9-9c30-a6aeb3c5c14c.png)

**Comment by akariv** [comment]
where is this `NgoOrgsLoop`? @noamoss

**Comment by noamoss** [comment]
@akariv ... not sure what you are asking

it is not implemented of course, since it would break the service. 
I showed you the code on one of our meetings - you looked at my code you said you know what is the issue and that my implementation is fine - and that's something you need. There is no difference betweeh the `NgoOrgsLoop` and the `GovOrgsLoop` - except for the parameter in the function.

**Comment by noamoss** [comment]
@akariv let me know if you need anything on this issue.

**Comment by noamoss** [comment]
@akariv please explain

**Comment by akariv** [comment]
The problem preventing loops in scripts using the method above (using prepare + next functions) was solved.

**Comment by noamoss** [comment]
@akariv tried compile my recursive functions  following the recentupdate  and got this error:
![image](https://user-images.githubusercontent.com/3581741/70835220-0ffb0400-1e05-11ea-999a-ab3aef905bfa.png), referring to

`      this.report
    ).pipe(
      switchMap((retval) => {
        if (retval === this.runner.COMPLETE) {
          this.content.addOptions(null, [
            { value: true, display: 'לחצו לסיום השיחה והצגת רשימת המשימות' },
          ]);
        } else {
          this.content.addOptions(null, [
            { value: true, display: 'השיחה הופסקה אולם תוכלו לחזור אליה בהמשך - לחצו להצגת רשימת המשימות' },
          ]);
        }
        return this.content.waitForInput(false);
      }),`

Notice I did not call the `false` it was on the repo, but it is probably related to your comment on https://github.com/hasadna/reportit-user/issues/41:


>If calling waitForInput inside a function, make sure to pass 'false' as a
parameter there.

**Comment by akariv** [comment]
npm install

**Comment by noamoss** [comment]
@akariv worked. 

Now my problem is how to quickly compile the local YAML into json, to check the functions are working well, and well integerated into the script - before making these changes on reportit-scripts and deploying to live.

I assume using the old  `yaml_to_json.py` convertor is the easiest way, right? If so, can you return it to this (and the user) repos?
If not, can you guide me how to perform script changes locally, for checks, before applying the on reportit-scripts?

**Comment by akariv** [comment]
That script is still in use in the reporit-sctipts repo, you can run it
there to compile the script from the builder without having to do a deploy.
The resulting json file can be then copied to the agent repo for testing
purposes.

**Comment by noamoss** [comment]
@akariv 

The current `yaml_to_json.py` is not working on the command line, as it includes newer features which (connection to firebase and kind of file) - I can't spend the time to debug it just to update the script locally. Hope we can think of a better way to enable local checks of the script.

**Comment by akariv** [comment]
If you don't include any other information other than 'not working' it's
not going to be easy to fix the issue you're seeing.

**Comment by noamoss** [comment]
it returns the following error:

>Traceback (most recent call last):
  File "yaml_to_json.py", line 173, in <module>
    yaml.dump(scripts, f_in.open('w'), allow_unicode=True, indent=2, width=1000000)
  File "/home/newone/anaconda3/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/home/newone/anaconda3/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'src/user/script.yaml'

but looking at the script shows why - it is built for local file anymore.

**Comment by noamoss** [comment]
I know it looks like I should just manually change the path - but it looks like much more than that when looking at the script.

**Comment by akariv** [comment]
You should run it from the root of the reporit-scripts repo, like so:

python tools/yaml_to_json.py

**Comment by noamoss** [comment]
closing this messy issue in favor of https://github.com/hasadna/reportit-agent/issues/70
