### ISSUE TITLE
typing a task comment/update, enter should rssault a line break, not a submit

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#56]
based on Saroj's feedback, when typing a comment/update in a task card, clicking enter is expected to add a line break, currently, it submits the comment.

![image](https://user-images.githubusercontent.com/3581741/68487598-0ac9f880-024c-11ea-9921-cc356176e9ac.png)

**Comment by noamoss** [comment]
@akariv checked and approved functionality, but the visual implementation should be repaired, as the submit button is hiding and actually I could not see it. Here is my suggestion:

![תמונה](https://user-images.githubusercontent.com/3581741/70796673-879c4500-1dab-11ea-9696-5dea87542c7c.png)

[whatismybrowser](whatismybrowser.com/w/6Q9EDZP)

**Comment by akariv** [comment]
Can you please share  a full screenshot?
Did you by any chance resize the text area?

**Comment by noamoss** [comment]
![תמונה](https://user-images.githubusercontent.com/3581741/70799069-4f980080-1db1-11ea-9bdb-30de8b9a622a.png)

>Did you by any chance resize the text area?

That what I thought - it worked/looked fine just when I zoomed out. CTRL+0 brought me back to this problem.

**Comment by noamoss** [comment]
checked and approved.
