### ISSUE TITLE
add "close report" button and script

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#61]
following pilot feedback, we would like to add the following usage scenario:

when an agent decides the report should be closed (become completed) they should bed able to click a button (see location below):

![image](https://user-images.githubusercontent.com/3581741/70465225-2afa0b00-1ac9-11ea-9d14-8c530915574b.png)

1. a pop up shows up and with a "yes"/"no" question: "האם את/ה מעוניין לסגור את הפניה" + a free text field labled "סיבת הסגירה"?
2a. clicked "no": close the popup.
2b. clicked "yes": 
2b1. add a new task "הטיפול בפניה הושלם". use the explanation field tet value as an update of the new task. mark the task as completed.
2b2. change report status to "completed".

![image](https://user-images.githubusercontent.com/3581741/70466627-38fd5b00-1acc-11ea-88cd-b6cb64f14505.png)

**Comment by noamoss** [comment]
(all the questions/answers/labels strings should be translatable, of course)

**Comment by akariv** [comment]
Should all tasks be marked as completed as well?

**Comment by noamoss** [comment]
checked and approved, Saroj will make another check.
