### ISSUE TITLE
English placeholder on a Hebrew itnerface

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#66]
https://admin.equality.org.il/#/report/187

![image](https://user-images.githubusercontent.com/3581741/70852235-d0d1bf00-1ea7-11ea-9d9a-9e18ee9a4e31.png)

**Comment by noamoss** [comment]
@akariv checked and approved.

can you paste the link for the placeholders on transifex? could not find them over there.

**Comment by akariv** [comment]
Look in the agent and user UI resources (not the scripts). I even
translated one of them to test.
